/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal()
}

dependencies {
    // Use TestNG framework, also requires calling test.useTestNG() below
    testImplementation(libs.testng)

    implementation(libs.clickhouseClient)

    // BOM used to keep versions consistent across all Arrow libraries
    implementation(platform(libs.arrowBom))
    implementation(libs.arrowVector)
    implementation(libs.arrowMemory)
    implementation(libs.arrowCompression)

    // Logging
    implementation(libs.slf4jSimple)
    implementation(libs.slf4jApi)

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.clickhouse.examples.arrow_format.ReadWriteArrow"
    applicationDefaultJvmArgs = listOf(
        "-Dorg.slf4j.simpleLogger.defaultLogLevel=INFO", // change to DEBUG to see wire data flow
        "--add-opens=java.base/java.nio=ALL-UNNAMED", // needed for Apache Arrow
        "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED", // needed for Apache Arrow
        "--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED" // needed for Apache Arrow
    )
}

tasks.named<Test>("test") {
    // Use TestNG for unit tests.
    useTestNG()
}
