/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use TestNG framework, also requires calling test.useTestNG() below
    testImplementation(libs.testng)

    // This dependency is used by the application.
    // Source: https://mvnrepository.com/artifact/org.apache.arrow/arrow-bom
    implementation(platform(libs.arrowBom))
    implementation(libs.arrowVector)
    implementation(libs.arrowMemory)
    implementation(libs.flightCore)
    implementation(libs.slf4jSimple)
    implementation(libs.slf4jApi)
    implementation(libs.adbcCore)

    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use TestNG for unit tests.
    useTestNG()
}
