package com.clickhouse.client.exception;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * All supported error codes defined in ClickHouse.
 */
public enum ClickHouseErrorCode {
    // grep -n '^[[:space:]]*M(' | sed -e
    // 's|^\([0-9]*\):[[:space:]]*M(\([0-9]*\),[[:space:]]*\([0-9A-Z_]*\)).*|\3(\2),
    // //
    // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L\1|g'
    OK(0), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L17
    UNSUPPORTED_METHOD(1), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L18
    UNSUPPORTED_PARAMETER(2), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L19
    UNEXPECTED_END_OF_FILE(3), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L20
    EXPECTED_END_OF_FILE(4), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L21
    CANNOT_PARSE_TEXT(6), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L22
    INCORRECT_NUMBER_OF_COLUMNS(7), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L23
    THERE_IS_NO_COLUMN(8), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L24
    SIZES_OF_COLUMNS_DOESNT_MATCH(9), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L25
    NOT_FOUND_COLUMN_IN_BLOCK(10), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L26
    POSITION_OUT_OF_BOUND(11), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L27
    PARAMETER_OUT_OF_BOUND(12), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L28
    SIZES_OF_COLUMNS_IN_TUPLE_DOESNT_MATCH(13), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L29
    DUPLICATE_COLUMN(15), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L30
    NO_SUCH_COLUMN_IN_TABLE(16), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L31
    DELIMITER_IN_STRING_LITERAL_DOESNT_MATCH(17), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L32
    CANNOT_INSERT_ELEMENT_INTO_CONSTANT_COLUMN(18), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L33
    SIZE_OF_FIXED_STRING_DOESNT_MATCH(19), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L34
    NUMBER_OF_COLUMNS_DOESNT_MATCH(20), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L35
    CANNOT_READ_ALL_DATA_FROM_TAB_SEPARATED_INPUT(21), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L36
    CANNOT_PARSE_ALL_VALUE_FROM_TAB_SEPARATED_INPUT(22), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L37
    CANNOT_READ_FROM_ISTREAM(23), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L38
    CANNOT_WRITE_TO_OSTREAM(24), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L39
    CANNOT_PARSE_ESCAPE_SEQUENCE(25), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L40
    CANNOT_PARSE_QUOTED_STRING(26), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L41
    CANNOT_PARSE_INPUT_ASSERTION_FAILED(27), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L42
    CANNOT_PRINT_FLOAT_OR_DOUBLE_NUMBER(28), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L43
    CANNOT_PRINT_INTEGER(29), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L44
    CANNOT_READ_SIZE_OF_COMPRESSED_CHUNK(30), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L45
    CANNOT_READ_COMPRESSED_CHUNK(31), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L46
    ATTEMPT_TO_READ_AFTER_EOF(32), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L47
    CANNOT_READ_ALL_DATA(33), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L48
    TOO_MANY_ARGUMENTS_FOR_FUNCTION(34), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L49
    TOO_FEW_ARGUMENTS_FOR_FUNCTION(35), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L50
    BAD_ARGUMENTS(36), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L51
    UNKNOWN_ELEMENT_IN_AST(37), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L52
    CANNOT_PARSE_DATE(38), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L53
    TOO_LARGE_SIZE_COMPRESSED(39), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L54
    CHECKSUM_DOESNT_MATCH(40), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L55
    CANNOT_PARSE_DATETIME(41), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L56
    NUMBER_OF_ARGUMENTS_DOESNT_MATCH(42), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L57
    ILLEGAL_TYPE_OF_ARGUMENT(43), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L58
    ILLEGAL_COLUMN(44), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L59
    ILLEGAL_NUMBER_OF_RESULT_COLUMNS(45), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L60
    UNKNOWN_FUNCTION(46), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L61
    UNKNOWN_IDENTIFIER(47), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L62
    NOT_IMPLEMENTED(48), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L63
    LOGICAL_ERROR(49), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L64
    UNKNOWN_TYPE(50), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L65
    EMPTY_LIST_OF_COLUMNS_QUERIED(51), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L66
    COLUMN_QUERIED_MORE_THAN_ONCE(52), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L67
    TYPE_MISMATCH(53), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L68
    STORAGE_DOESNT_ALLOW_PARAMETERS(54), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L69
    STORAGE_REQUIRES_PARAMETER(55), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L70
    UNKNOWN_STORAGE(56), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L71
    TABLE_ALREADY_EXISTS(57), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L72
    TABLE_METADATA_ALREADY_EXISTS(58), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L73
    ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER(59), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L74
    UNKNOWN_TABLE(60), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L75
    ONLY_FILTER_COLUMN_IN_BLOCK(61), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L76
    SYNTAX_ERROR(62), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L77
    UNKNOWN_AGGREGATE_FUNCTION(63), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L78
    CANNOT_READ_AGGREGATE_FUNCTION_FROM_TEXT(64), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L79
    CANNOT_WRITE_AGGREGATE_FUNCTION_AS_TEXT(65), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L80
    NOT_A_COLUMN(66), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L81
    ILLEGAL_KEY_OF_AGGREGATION(67), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L82
    CANNOT_GET_SIZE_OF_FIELD(68), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L83
    ARGUMENT_OUT_OF_BOUND(69), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L84
    CANNOT_CONVERT_TYPE(70), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L85
    CANNOT_WRITE_AFTER_END_OF_BUFFER(71), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L86
    CANNOT_PARSE_NUMBER(72), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L87
    UNKNOWN_FORMAT(73), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L88
    CANNOT_READ_FROM_FILE_DESCRIPTOR(74), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L89
    CANNOT_WRITE_TO_FILE_DESCRIPTOR(75), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L90
    CANNOT_OPEN_FILE(76), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L91
    CANNOT_CLOSE_FILE(77), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L92
    UNKNOWN_TYPE_OF_QUERY(78), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L93
    INCORRECT_FILE_NAME(79), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L94
    INCORRECT_QUERY(80), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L95
    UNKNOWN_DATABASE(81), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L96
    DATABASE_ALREADY_EXISTS(82), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L97
    DIRECTORY_DOESNT_EXIST(83), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L98
    DIRECTORY_ALREADY_EXISTS(84), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L99
    FORMAT_IS_NOT_SUITABLE_FOR_INPUT(85), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L100
    RECEIVED_ERROR_FROM_REMOTE_IO_SERVER(86), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L101
    CANNOT_SEEK_THROUGH_FILE(87), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L102
    CANNOT_TRUNCATE_FILE(88), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L103
    UNKNOWN_COMPRESSION_METHOD(89), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L104
    EMPTY_LIST_OF_COLUMNS_PASSED(90), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L105
    SIZES_OF_MARKS_FILES_ARE_INCONSISTENT(91), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L106
    EMPTY_DATA_PASSED(92), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L107
    UNKNOWN_AGGREGATED_DATA_VARIANT(93), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L108
    CANNOT_MERGE_DIFFERENT_AGGREGATED_DATA_VARIANTS(94), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L109
    CANNOT_READ_FROM_SOCKET(95), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L110
    CANNOT_WRITE_TO_SOCKET(96), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L111
    CANNOT_READ_ALL_DATA_FROM_CHUNKED_INPUT(97), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L112
    CANNOT_WRITE_TO_EMPTY_BLOCK_OUTPUT_STREAM(98), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L113
    UNKNOWN_PACKET_FROM_CLIENT(99), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L114
    UNKNOWN_PACKET_FROM_SERVER(100), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L115
    UNEXPECTED_PACKET_FROM_CLIENT(101), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L116
    UNEXPECTED_PACKET_FROM_SERVER(102), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L117
    RECEIVED_DATA_FOR_WRONG_QUERY_ID(103), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L118
    TOO_SMALL_BUFFER_SIZE(104), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L119
    CANNOT_READ_HISTORY(105), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L120
    CANNOT_APPEND_HISTORY(106), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L121
    FILE_DOESNT_EXIST(107), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L122
    NO_DATA_TO_INSERT(108), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L123
    CANNOT_BLOCK_SIGNAL(109), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L124
    CANNOT_UNBLOCK_SIGNAL(110), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L125
    CANNOT_MANIPULATE_SIGSET(111), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L126
    CANNOT_WAIT_FOR_SIGNAL(112), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L127
    THERE_IS_NO_SESSION(113), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L128
    CANNOT_CLOCK_GETTIME(114), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L129
    UNKNOWN_SETTING(115), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L130
    THERE_IS_NO_DEFAULT_VALUE(116), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L131
    INCORRECT_DATA(117), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L132
    ENGINE_REQUIRED(119), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L133
    CANNOT_INSERT_VALUE_OF_DIFFERENT_SIZE_INTO_TUPLE(120), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L134
    UNSUPPORTED_JOIN_KEYS(121), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L135
    INCOMPATIBLE_COLUMNS(122), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L136
    UNKNOWN_TYPE_OF_AST_NODE(123), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L137
    INCORRECT_ELEMENT_OF_SET(124), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L138
    INCORRECT_RESULT_OF_SCALAR_SUBQUERY(125), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L139
    CANNOT_GET_RETURN_TYPE(126), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L140
    ILLEGAL_INDEX(127), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L141
    TOO_LARGE_ARRAY_SIZE(128), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L142
    FUNCTION_IS_SPECIAL(129), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L143
    CANNOT_READ_ARRAY_FROM_TEXT(130), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L144
    TOO_LARGE_STRING_SIZE(131), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L145
    AGGREGATE_FUNCTION_DOESNT_ALLOW_PARAMETERS(133), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L146
    PARAMETERS_TO_AGGREGATE_FUNCTIONS_MUST_BE_LITERALS(134), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L147
    ZERO_ARRAY_OR_TUPLE_INDEX(135), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L148
    UNKNOWN_ELEMENT_IN_CONFIG(137), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L149
    EXCESSIVE_ELEMENT_IN_CONFIG(138), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L150
    NO_ELEMENTS_IN_CONFIG(139), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L151
    ALL_REQUESTED_COLUMNS_ARE_MISSING(140), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L152
    SAMPLING_NOT_SUPPORTED(141), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L153
    NOT_FOUND_NODE(142), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L154
    FOUND_MORE_THAN_ONE_NODE(143), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L155
    FIRST_DATE_IS_BIGGER_THAN_LAST_DATE(144), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L156
    UNKNOWN_OVERFLOW_MODE(145), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L157
    QUERY_SECTION_DOESNT_MAKE_SENSE(146), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L158
    NOT_FOUND_FUNCTION_ELEMENT_FOR_AGGREGATE(147), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L159
    NOT_FOUND_RELATION_ELEMENT_FOR_CONDITION(148), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L160
    NOT_FOUND_RHS_ELEMENT_FOR_CONDITION(149), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L161
    EMPTY_LIST_OF_ATTRIBUTES_PASSED(150), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L162
    INDEX_OF_COLUMN_IN_SORT_CLAUSE_IS_OUT_OF_RANGE(151), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L163
    UNKNOWN_DIRECTION_OF_SORTING(152), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L164
    ILLEGAL_DIVISION(153), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L165
    AGGREGATE_FUNCTION_NOT_APPLICABLE(154), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L166
    UNKNOWN_RELATION(155), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L167
    DICTIONARIES_WAS_NOT_LOADED(156), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L168
    ILLEGAL_OVERFLOW_MODE(157), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L169
    TOO_MANY_ROWS(158), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L170
    TIMEOUT_EXCEEDED(159), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L171
    TOO_SLOW(160), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L172
    TOO_MANY_COLUMNS(161), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L173
    TOO_DEEP_SUBQUERIES(162), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L174
    TOO_DEEP_PIPELINE(163), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L175
    READONLY(164), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L176
    TOO_MANY_TEMPORARY_COLUMNS(165), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L177
    TOO_MANY_TEMPORARY_NON_CONST_COLUMNS(166), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L178
    TOO_DEEP_AST(167), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L179
    TOO_BIG_AST(168), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L180
    BAD_TYPE_OF_FIELD(169), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L181
    BAD_GET(170), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L182
    CANNOT_CREATE_DIRECTORY(172), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L183
    CANNOT_ALLOCATE_MEMORY(173), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L184
    CYCLIC_ALIASES(174), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L185
    CHUNK_NOT_FOUND(176), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L186
    DUPLICATE_CHUNK_NAME(177), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L187
    MULTIPLE_ALIASES_FOR_EXPRESSION(178), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L188
    MULTIPLE_EXPRESSIONS_FOR_ALIAS(179), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L189
    THERE_IS_NO_PROFILE(180), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L190
    ILLEGAL_FINAL(181), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L191
    ILLEGAL_PREWHERE(182), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L192
    UNEXPECTED_EXPRESSION(183), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L193
    ILLEGAL_AGGREGATION(184), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L194
    UNSUPPORTED_MYISAM_BLOCK_TYPE(185), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L195
    UNSUPPORTED_COLLATION_LOCALE(186), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L196
    COLLATION_COMPARISON_FAILED(187), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L197
    UNKNOWN_ACTION(188), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L198
    TABLE_MUST_NOT_BE_CREATED_MANUALLY(189), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L199
    SIZES_OF_ARRAYS_DOESNT_MATCH(190), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L200
    SET_SIZE_LIMIT_EXCEEDED(191), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L201
    UNKNOWN_USER(192), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L202
    WRONG_PASSWORD(193), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L203
    REQUIRED_PASSWORD(194), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L204
    IP_ADDRESS_NOT_ALLOWED(195), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L205
    UNKNOWN_ADDRESS_PATTERN_TYPE(196), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L206
    SERVER_REVISION_IS_TOO_OLD(197), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L207
    DNS_ERROR(198), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L208
    UNKNOWN_QUOTA(199), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L209
    QUOTA_DOESNT_ALLOW_KEYS(200), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L210
    QUOTA_EXPIRED(201), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L211
    TOO_MANY_SIMULTANEOUS_QUERIES(202), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L212
    NO_FREE_CONNECTION(203), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L213
    CANNOT_FSYNC(204), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L214
    NESTED_TYPE_TOO_DEEP(205), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L215
    ALIAS_REQUIRED(206), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L216
    AMBIGUOUS_IDENTIFIER(207), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L217
    EMPTY_NESTED_TABLE(208), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L218
    SOCKET_TIMEOUT(209), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L219
    NETWORK_ERROR(210), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L220
    EMPTY_QUERY(211), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L221
    UNKNOWN_LOAD_BALANCING(212), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L222
    UNKNOWN_TOTALS_MODE(213), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L223
    CANNOT_STATVFS(214), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L224
    NOT_AN_AGGREGATE(215), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L225
    QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING(216), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L226
    CLIENT_HAS_CONNECTED_TO_WRONG_PORT(217), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L227
    TABLE_IS_DROPPED(218), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L228
    DATABASE_NOT_EMPTY(219), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L229
    DUPLICATE_INTERSERVER_IO_ENDPOINT(220), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L230
    NO_SUCH_INTERSERVER_IO_ENDPOINT(221), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L231
    ADDING_REPLICA_TO_NON_EMPTY_TABLE(222), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L232
    UNEXPECTED_AST_STRUCTURE(223), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L233
    REPLICA_IS_ALREADY_ACTIVE(224), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L234
    NO_ZOOKEEPER(225), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L235
    NO_FILE_IN_DATA_PART(226), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L236
    UNEXPECTED_FILE_IN_DATA_PART(227), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L237
    BAD_SIZE_OF_FILE_IN_DATA_PART(228), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L238
    QUERY_IS_TOO_LARGE(229), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L239
    NOT_FOUND_EXPECTED_DATA_PART(230), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L240
    TOO_MANY_UNEXPECTED_DATA_PARTS(231), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L241
    NO_SUCH_DATA_PART(232), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L242
    BAD_DATA_PART_NAME(233), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L243
    NO_REPLICA_HAS_PART(234), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L244
    DUPLICATE_DATA_PART(235), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L245
    ABORTED(236), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L246
    NO_REPLICA_NAME_GIVEN(237), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L247
    FORMAT_VERSION_TOO_OLD(238), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L248
    CANNOT_MUNMAP(239), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L249
    CANNOT_MREMAP(240), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L250
    MEMORY_LIMIT_EXCEEDED(241), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L251
    TABLE_IS_READ_ONLY(242), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L252
    NOT_ENOUGH_SPACE(243), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L253
    UNEXPECTED_ZOOKEEPER_ERROR(244), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L254
    CORRUPTED_DATA(246), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L255
    INCORRECT_MARK(247), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L256
    INVALID_PARTITION_VALUE(248), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L257
    NOT_ENOUGH_BLOCK_NUMBERS(250), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L258
    NO_SUCH_REPLICA(251), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L259
    TOO_MANY_PARTS(252), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L260
    REPLICA_IS_ALREADY_EXIST(253), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L261
    NO_ACTIVE_REPLICAS(254), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L262
    TOO_MANY_RETRIES_TO_FETCH_PARTS(255), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L263
    PARTITION_ALREADY_EXISTS(256), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L264
    PARTITION_DOESNT_EXIST(257), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L265
    UNION_ALL_RESULT_STRUCTURES_MISMATCH(258), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L266
    CLIENT_OUTPUT_FORMAT_SPECIFIED(260), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L267
    UNKNOWN_BLOCK_INFO_FIELD(261), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L268
    BAD_COLLATION(262), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L269
    CANNOT_COMPILE_CODE(263), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L270
    INCOMPATIBLE_TYPE_OF_JOIN(264), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L271
    NO_AVAILABLE_REPLICA(265), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L272
    MISMATCH_REPLICAS_DATA_SOURCES(266), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L273
    STORAGE_DOESNT_SUPPORT_PARALLEL_REPLICAS(267), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L274
    CPUID_ERROR(268), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L275
    INFINITE_LOOP(269), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L276
    CANNOT_COMPRESS(270), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L277
    CANNOT_DECOMPRESS(271), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L278
    CANNOT_IO_SUBMIT(272), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L279
    CANNOT_IO_GETEVENTS(273), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L280
    AIO_READ_ERROR(274), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L281
    AIO_WRITE_ERROR(275), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L282
    INDEX_NOT_USED(277), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L283
    ALL_CONNECTION_TRIES_FAILED(279), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L284
    NO_AVAILABLE_DATA(280), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L285
    DICTIONARY_IS_EMPTY(281), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L286
    INCORRECT_INDEX(282), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L287
    UNKNOWN_DISTRIBUTED_PRODUCT_MODE(283), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L288
    WRONG_GLOBAL_SUBQUERY(284), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L289
    TOO_FEW_LIVE_REPLICAS(285), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L290
    UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE(286), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L291
    UNKNOWN_FORMAT_VERSION(287), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L292
    DISTRIBUTED_IN_JOIN_SUBQUERY_DENIED(288), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L293
    REPLICA_IS_NOT_IN_QUORUM(289), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L294
    LIMIT_EXCEEDED(290), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L295
    DATABASE_ACCESS_DENIED(291), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L296
    MONGODB_CANNOT_AUTHENTICATE(293), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L297
    INVALID_BLOCK_EXTRA_INFO(294), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L298
    RECEIVED_EMPTY_DATA(295), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L299
    NO_REMOTE_SHARD_FOUND(296), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L300
    SHARD_HAS_NO_CONNECTIONS(297), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L301
    CANNOT_PIPE(298), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L302
    CANNOT_FORK(299), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L303
    CANNOT_DLSYM(300), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L304
    CANNOT_CREATE_CHILD_PROCESS(301), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L305
    CHILD_WAS_NOT_EXITED_NORMALLY(302), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L306
    CANNOT_SELECT(303), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L307
    CANNOT_WAITPID(304), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L308
    TABLE_WAS_NOT_DROPPED(305), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L309
    TOO_DEEP_RECURSION(306), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L310
    TOO_MANY_BYTES(307), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L311
    UNEXPECTED_NODE_IN_ZOOKEEPER(308), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L312
    FUNCTION_CANNOT_HAVE_PARAMETERS(309), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L313
    INVALID_SHARD_WEIGHT(317), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L314
    INVALID_CONFIG_PARAMETER(318), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L315
    UNKNOWN_STATUS_OF_INSERT(319), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L316
    VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE(321), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L317
    BARRIER_TIMEOUT(335), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L318
    UNKNOWN_DATABASE_ENGINE(336), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L319
    DDL_GUARD_IS_ACTIVE(337), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L320
    UNFINISHED(341), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L321
    METADATA_MISMATCH(342), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L322
    SUPPORT_IS_DISABLED(344), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L323
    TABLE_DIFFERS_TOO_MUCH(345), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L324
    CANNOT_CONVERT_CHARSET(346), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L325
    CANNOT_LOAD_CONFIG(347), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L326
    CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN(349), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L327
    INCOMPATIBLE_SOURCE_TABLES(350), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L328
    AMBIGUOUS_TABLE_NAME(351), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L329
    AMBIGUOUS_COLUMN_NAME(352), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L330
    INDEX_OF_POSITIONAL_ARGUMENT_IS_OUT_OF_RANGE(353), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L331
    ZLIB_INFLATE_FAILED(354), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L332
    ZLIB_DEFLATE_FAILED(355), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L333
    BAD_LAMBDA(356), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L334
    RESERVED_IDENTIFIER_NAME(357), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L335
    INTO_OUTFILE_NOT_ALLOWED(358), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L336
    TABLE_SIZE_EXCEEDS_MAX_DROP_SIZE_LIMIT(359), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L337
    CANNOT_CREATE_CHARSET_CONVERTER(360), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L338
    SEEK_POSITION_OUT_OF_BOUND(361), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L339
    CURRENT_WRITE_BUFFER_IS_EXHAUSTED(362), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L340
    CANNOT_CREATE_IO_BUFFER(363), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L341
    RECEIVED_ERROR_TOO_MANY_REQUESTS(364), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L342
    SIZES_OF_NESTED_COLUMNS_ARE_INCONSISTENT(366), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L343
    TOO_MANY_FETCHES(367), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L344
    ALL_REPLICAS_ARE_STALE(369), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L345
    DATA_TYPE_CANNOT_BE_USED_IN_TABLES(370), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L346
    INCONSISTENT_CLUSTER_DEFINITION(371), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L347
    SESSION_NOT_FOUND(372), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L348
    SESSION_IS_LOCKED(373), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L349
    INVALID_SESSION_TIMEOUT(374), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L350
    CANNOT_DLOPEN(375), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L351
    CANNOT_PARSE_UUID(376), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L352
    ILLEGAL_SYNTAX_FOR_DATA_TYPE(377), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L353
    DATA_TYPE_CANNOT_HAVE_ARGUMENTS(378), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L354
    UNKNOWN_STATUS_OF_DISTRIBUTED_DDL_TASK(379), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L355
    CANNOT_KILL(380), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L356
    HTTP_LENGTH_REQUIRED(381), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L357
    CANNOT_LOAD_CATBOOST_MODEL(382), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L358
    CANNOT_APPLY_CATBOOST_MODEL(383), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L359
    PART_IS_TEMPORARILY_LOCKED(384), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L360
    MULTIPLE_STREAMS_REQUIRED(385), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L361
    NO_COMMON_TYPE(386), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L362
    DICTIONARY_ALREADY_EXISTS(387), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L363
    CANNOT_ASSIGN_OPTIMIZE(388), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L364
    INSERT_WAS_DEDUPLICATED(389), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L365
    CANNOT_GET_CREATE_TABLE_QUERY(390), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L366
    EXTERNAL_LIBRARY_ERROR(391), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L367
    QUERY_IS_PROHIBITED(392), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L368
    THERE_IS_NO_QUERY(393), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L369
    QUERY_WAS_CANCELLED(394), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L370
    FUNCTION_THROW_IF_VALUE_IS_NON_ZERO(395), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L371
    TOO_MANY_ROWS_OR_BYTES(396), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L372
    QUERY_IS_NOT_SUPPORTED_IN_MATERIALIZED_VIEW(397), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L373
    UNKNOWN_MUTATION_COMMAND(398), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L374
    FORMAT_IS_NOT_SUITABLE_FOR_OUTPUT(399), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L375
    CANNOT_STAT(400), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L376
    FEATURE_IS_NOT_ENABLED_AT_BUILD_TIME(401), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L377
    CANNOT_IOSETUP(402), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L378
    INVALID_JOIN_ON_EXPRESSION(403), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L379
    BAD_ODBC_CONNECTION_STRING(404), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L380
    PARTITION_SIZE_EXCEEDS_MAX_DROP_SIZE_LIMIT(405), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L381
    TOP_AND_LIMIT_TOGETHER(406), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L382
    DECIMAL_OVERFLOW(407), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L383
    BAD_REQUEST_PARAMETER(408), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L384
    EXTERNAL_EXECUTABLE_NOT_FOUND(409), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L385
    EXTERNAL_SERVER_IS_NOT_RESPONDING(410), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L386
    PTHREAD_ERROR(411), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L387
    NETLINK_ERROR(412), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L388
    CANNOT_SET_SIGNAL_HANDLER(413), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L389
    ALL_REPLICAS_LOST(415), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L390
    REPLICA_STATUS_CHANGED(416), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L391
    EXPECTED_ALL_OR_ANY(417), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L392
    UNKNOWN_JOIN(418), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L393
    MULTIPLE_ASSIGNMENTS_TO_COLUMN(419), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L394
    CANNOT_UPDATE_COLUMN(420), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L395
    CANNOT_ADD_DIFFERENT_AGGREGATE_STATES(421), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L396
    UNSUPPORTED_URI_SCHEME(422), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L397
    CANNOT_GETTIMEOFDAY(423), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L398
    CANNOT_LINK(424), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L399
    SYSTEM_ERROR(425), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L400
    CANNOT_COMPILE_REGEXP(427), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L401
    UNKNOWN_LOG_LEVEL(428), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L402
    FAILED_TO_GETPWUID(429), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L403
    MISMATCHING_USERS_FOR_PROCESS_AND_DATA(430), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L404
    ILLEGAL_SYNTAX_FOR_CODEC_TYPE(431), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L405
    UNKNOWN_CODEC(432), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L406
    ILLEGAL_CODEC_PARAMETER(433), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L407
    CANNOT_PARSE_PROTOBUF_SCHEMA(434), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L408
    NO_COLUMN_SERIALIZED_TO_REQUIRED_PROTOBUF_FIELD(435), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L409
    PROTOBUF_BAD_CAST(436), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L410
    PROTOBUF_FIELD_NOT_REPEATED(437), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L411
    DATA_TYPE_CANNOT_BE_PROMOTED(438), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L412
    CANNOT_SCHEDULE_TASK(439), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L413
    INVALID_LIMIT_EXPRESSION(440), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L414
    CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING(441), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L415
    BAD_DATABASE_FOR_TEMPORARY_TABLE(442), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L416
    NO_COLUMNS_SERIALIZED_TO_PROTOBUF_FIELDS(443), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L417
    UNKNOWN_PROTOBUF_FORMAT(444), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L418
    CANNOT_MPROTECT(445), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L419
    FUNCTION_NOT_ALLOWED(446), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L420
    HYPERSCAN_CANNOT_SCAN_TEXT(447), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L421
    BROTLI_READ_FAILED(448), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L422
    BROTLI_WRITE_FAILED(449), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L423
    BAD_TTL_EXPRESSION(450), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L424
    BAD_TTL_FILE(451), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L425
    SETTING_CONSTRAINT_VIOLATION(452), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L426
    MYSQL_CLIENT_INSUFFICIENT_CAPABILITIES(453), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L427
    OPENSSL_ERROR(454), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L428
    SUSPICIOUS_TYPE_FOR_LOW_CARDINALITY(455), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L429
    UNKNOWN_QUERY_PARAMETER(456), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L430
    BAD_QUERY_PARAMETER(457), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L431
    CANNOT_UNLINK(458), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L432
    CANNOT_SET_THREAD_PRIORITY(459), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L433
    CANNOT_CREATE_TIMER(460), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L434
    CANNOT_SET_TIMER_PERIOD(461), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L435
    CANNOT_DELETE_TIMER(462), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L436
    CANNOT_FCNTL(463), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L437
    CANNOT_PARSE_ELF(464), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L438
    CANNOT_PARSE_DWARF(465), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L439
    INSECURE_PATH(466), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L440
    CANNOT_PARSE_BOOL(467), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L441
    CANNOT_PTHREAD_ATTR(468), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L442
    VIOLATED_CONSTRAINT(469), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L443
    QUERY_IS_NOT_SUPPORTED_IN_LIVE_VIEW(470), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L444
    INVALID_SETTING_VALUE(471), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L445
    READONLY_SETTING(472), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L446
    DEADLOCK_AVOIDED(473), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L447
    INVALID_TEMPLATE_FORMAT(474), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L448
    INVALID_WITH_FILL_EXPRESSION(475), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L449
    WITH_TIES_WITHOUT_ORDER_BY(476), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L450
    INVALID_USAGE_OF_INPUT(477), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L451
    UNKNOWN_POLICY(478), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L452
    UNKNOWN_DISK(479), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L453
    UNKNOWN_PROTOCOL(480), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L454
    PATH_ACCESS_DENIED(481), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L455
    DICTIONARY_ACCESS_DENIED(482), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L456
    TOO_MANY_REDIRECTS(483), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L457
    INTERNAL_REDIS_ERROR(484), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L458
    SCALAR_ALREADY_EXISTS(485), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L459
    CANNOT_GET_CREATE_DICTIONARY_QUERY(487), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L460
    UNKNOWN_DICTIONARY(488), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L461
    INCORRECT_DICTIONARY_DEFINITION(489), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L462
    CANNOT_FORMAT_DATETIME(490), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L463
    UNACCEPTABLE_URL(491), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L464
    ACCESS_ENTITY_NOT_FOUND(492), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L465
    ACCESS_ENTITY_ALREADY_EXISTS(493), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L466
    ACCESS_ENTITY_FOUND_DUPLICATES(494), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L467
    ACCESS_STORAGE_READONLY(495), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L468
    QUOTA_REQUIRES_CLIENT_KEY(496), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L469
    ACCESS_DENIED(497), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L470
    LIMIT_BY_WITH_TIES_IS_NOT_SUPPORTED(498), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L471
    S3_ERROR(499), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L472
    CANNOT_CREATE_DATABASE(501), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L473
    CANNOT_SIGQUEUE(502), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L474
    AGGREGATE_FUNCTION_THROW(503), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L475
    FILE_ALREADY_EXISTS(504), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L476
    CANNOT_DELETE_DIRECTORY(505), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L477
    UNEXPECTED_ERROR_CODE(506), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L478
    UNABLE_TO_SKIP_UNUSED_SHARDS(507), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L479
    UNKNOWN_ACCESS_TYPE(508), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L480
    INVALID_GRANT(509), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L481
    CACHE_DICTIONARY_UPDATE_FAIL(510), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L482
    UNKNOWN_ROLE(511), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L483
    SET_NON_GRANTED_ROLE(512), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L484
    UNKNOWN_PART_TYPE(513), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L485
    ACCESS_STORAGE_FOR_INSERTION_NOT_FOUND(514), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L486
    INCORRECT_ACCESS_ENTITY_DEFINITION(515), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L487
    AUTHENTICATION_FAILED(516), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L488
    CANNOT_ASSIGN_ALTER(517), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L489
    CANNOT_COMMIT_OFFSET(518), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L490
    NO_REMOTE_SHARD_AVAILABLE(519), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L491
    CANNOT_DETACH_DICTIONARY_AS_TABLE(520), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L492
    ATOMIC_RENAME_FAIL(521), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L493
    UNKNOWN_ROW_POLICY(523), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L494
    ALTER_OF_COLUMN_IS_FORBIDDEN(524), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L495
    INCORRECT_DISK_INDEX(525), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L496
    NO_SUITABLE_FUNCTION_IMPLEMENTATION(527), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L497
    CASSANDRA_INTERNAL_ERROR(528), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L498
    NOT_A_LEADER(529), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L499
    CANNOT_CONNECT_RABBITMQ(530), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L500
    CANNOT_FSTAT(531), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L501
    LDAP_ERROR(532), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L502
    INCONSISTENT_RESERVATIONS(533), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L503
    NO_RESERVATIONS_PROVIDED(534), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L504
    UNKNOWN_RAID_TYPE(535), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L505
    CANNOT_RESTORE_FROM_FIELD_DUMP(536), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L506
    ILLEGAL_MYSQL_VARIABLE(537), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L507
    MYSQL_SYNTAX_ERROR(538), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L508
    CANNOT_BIND_RABBITMQ_EXCHANGE(539), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L509
    CANNOT_DECLARE_RABBITMQ_EXCHANGE(540), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L510
    CANNOT_CREATE_RABBITMQ_QUEUE_BINDING(541), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L511
    CANNOT_REMOVE_RABBITMQ_EXCHANGE(542), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L512
    UNKNOWN_MYSQL_DATATYPES_SUPPORT_LEVEL(543), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L513
    ROW_AND_ROWS_TOGETHER(544), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L514
    FIRST_AND_NEXT_TOGETHER(545), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L515
    NO_ROW_DELIMITER(546), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L516
    INVALID_RAID_TYPE(547), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L517
    UNKNOWN_VOLUME(548), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L518
    DATA_TYPE_CANNOT_BE_USED_IN_KEY(549), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L519
    CONDITIONAL_TREE_PARENT_NOT_FOUND(550), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L520
    ILLEGAL_PROJECTION_MANIPULATOR(551), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L521
    UNRECOGNIZED_ARGUMENTS(552), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L522
    LZMA_STREAM_ENCODER_FAILED(553), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L523
    LZMA_STREAM_DECODER_FAILED(554), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L524
    ROCKSDB_ERROR(555), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L525
    SYNC_MYSQL_USER_ACCESS_ERROR(556), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L526
    UNKNOWN_UNION(557), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L527
    EXPECTED_ALL_OR_DISTINCT(558), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L528
    INVALID_GRPC_QUERY_INFO(559), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L529
    ZSTD_ENCODER_FAILED(560), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L530
    ZSTD_DECODER_FAILED(561), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L531
    TLD_LIST_NOT_FOUND(562), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L532
    CANNOT_READ_MAP_FROM_TEXT(563), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L533
    INTERSERVER_SCHEME_DOESNT_MATCH(564), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L534
    TOO_MANY_PARTITIONS(565), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L535
    CANNOT_RMDIR(566), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L536
    DUPLICATED_PART_UUIDS(567), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L537
    RAFT_ERROR(568), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L538
    MULTIPLE_COLUMNS_SERIALIZED_TO_SAME_PROTOBUF_FIELD(569), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L539
    DATA_TYPE_INCOMPATIBLE_WITH_PROTOBUF_FIELD(570), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L540
    DATABASE_REPLICATION_FAILED(571), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L541
    TOO_MANY_QUERY_PLAN_OPTIMIZATIONS(572), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L542
    EPOLL_ERROR(573), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L543
    DISTRIBUTED_TOO_MANY_PENDING_BYTES(574), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L544
    UNKNOWN_SNAPSHOT(575), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L545
    KERBEROS_ERROR(576), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L546
    INVALID_SHARD_ID(577), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L547
    INVALID_FORMAT_INSERT_QUERY_WITH_DATA(578), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L548
    INCORRECT_PART_TYPE(579), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L549
    CANNOT_SET_ROUNDING_MODE(580), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L550
    TOO_LARGE_DISTRIBUTED_DEPTH(581), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L551
    NO_SUCH_PROJECTION_IN_TABLE(582), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L552
    ILLEGAL_PROJECTION(583), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L553
    PROJECTION_NOT_USED(584), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L554
    CANNOT_PARSE_YAML(585), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L555
    CANNOT_CREATE_FILE(586), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L556
    CONCURRENT_ACCESS_NOT_SUPPORTED(587), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L557
    DISTRIBUTED_BROKEN_BATCH_INFO(588), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L558
    DISTRIBUTED_BROKEN_BATCH_FILES(589), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L559
    CANNOT_SYSCONF(590), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L560
    SQLITE_ENGINE_ERROR(591), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L561
    DATA_ENCRYPTION_ERROR(592), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L562
    ZERO_COPY_REPLICATION_ERROR(593), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L563
    BZIP2_STREAM_DECODER_FAILED(594), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L564
    BZIP2_STREAM_ENCODER_FAILED(595), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L565
    INTERSECT_OR_EXCEPT_RESULT_STRUCTURES_MISMATCH(596), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L566
    NO_SUCH_ERROR_CODE(597), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L567
    BACKUP_ALREADY_EXISTS(598), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L568
    BACKUP_NOT_FOUND(599), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L569
    BACKUP_VERSION_NOT_SUPPORTED(600), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L570
    BACKUP_DAMAGED(601), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L571
    NO_BASE_BACKUP(602), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L572
    WRONG_BASE_BACKUP(603), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L573
    BACKUP_ENTRY_ALREADY_EXISTS(604), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L574
    BACKUP_ENTRY_NOT_FOUND(605), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L575
    BACKUP_IS_EMPTY(606), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L576
    BACKUP_ELEMENT_DUPLICATE(607), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L577
    CANNOT_RESTORE_TABLE(608), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L578
    FUNCTION_ALREADY_EXISTS(609), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L579
    CANNOT_DROP_SYSTEM_FUNCTION(610), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L580
    CANNOT_CREATE_RECURSIVE_FUNCTION(611), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L581
    OBJECT_ALREADY_STORED_ON_DISK(612), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L582
    OBJECT_WAS_NOT_STORED_ON_DISK(613), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L583
    POSTGRESQL_CONNECTION_FAILURE(614), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L584
    CANNOT_ADVISE(615), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L585
    UNKNOWN_READ_METHOD(616), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L586
    LZ4_ENCODER_FAILED(617), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L587
    LZ4_DECODER_FAILED(618), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L588
    POSTGRESQL_REPLICATION_INTERNAL_ERROR(619), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L589
    QUERY_NOT_ALLOWED(620), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L590
    KEEPER_EXCEPTION(999), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L592
    POCO_EXCEPTION(1000), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L593
    STD_EXCEPTION(1001), // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L594
    UNKNOWN_EXCEPTION(1002); // https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp#L595

    private static final Map<Integer, ClickHouseErrorCode> byCodes;

    static {
        Map<Integer, ClickHouseErrorCode> map = new HashMap<>();
        for (ClickHouseErrorCode errorCode : values()) {
            map.put(errorCode.code, errorCode);
        }
        byCodes = Collections.unmodifiableMap(map);
    }

    public final Integer code;

    ClickHouseErrorCode(Integer code) {
        this.code = code;
    }

    public static ClickHouseErrorCode fromCode(Integer code) {
        return fromCodeOrDefault(code, null);
    }

    public static ClickHouseErrorCode fromCodeOrDefault(Integer code, ClickHouseErrorCode defaultErrorCode) {
        return byCodes.getOrDefault(code, defaultErrorCode);
    }

    @Override
    public String toString() {
        return name() + " (code " + code + ')';
    }
}
