/*
 * This source file was generated by the Gradle 'init' task
 */
package com.clickhouse.examples.arrow_server;

import org.apache.arrow.flight.FlightServer;
import org.apache.arrow.flight.Location;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppArrowServer {

    private static final Logger LOG = LoggerFactory.getLogger(AppArrowServer.class);

    final FlightServer flightServer;
    final Location location;


    AppArrowServer() {

        location = Location.forGrpcInsecure("0.0.0.0", 33333);
        flightServer = FlightServer.builder()
                .location(location)
                .build();
    }


    void start() {
        try {
            flightServer.start();
        } catch (Exception e) {
            LOG.error("failed to start flight server at location " + location, e);
        }

        LOG.info("Flight server started at {}", location);

        try {
            flightServer.awaitTermination();
        } catch (InterruptedException e) {
            LOG.info("Process was interrupted");
        }
    }

    public static void main(String[] args) {
        AppArrowServer appServer = new AppArrowServer();


        appServer.start();
    }
}
