// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/proto/ui_stats_event.proto
// Protobuf Java Version: 4.27.1

package com.clickhouse.examples.protos;

public interface UIEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UIEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string session_id = 3;</code>
   * @return The sessionId.
   */
  String getSessionId();
  /**
   * <code>string session_id = 3;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int64 duration = 5;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>string event = 6;</code>
   * @return The event.
   */
  String getEvent();
  /**
   * <code>string event = 6;</code>
   * @return The bytes for event.
   */
  com.google.protobuf.ByteString
      getEventBytes();
}
