// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/proto/ui_stats_event.proto
// Protobuf Java Version: 4.27.1

package com.clickhouse.examples.protos;

public final class UIStatsEventProtos {
  private UIStatsEventProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      UIStatsEventProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UIEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UIEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036src/proto/ui_stats_event.proto\"o\n\007UIEv" +
      "ent\022\013\n\003url\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022\022\n\nses" +
      "sion_id\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\022\020\n\010dura" +
      "tion\030\005 \001(\003\022\r\n\005event\030\006 \001(\tB5\n\035com.clickho" +
      "use.samples.protosB\022UIStatsEventProtosP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UIEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UIEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UIEvent_descriptor,
        new String[] { "Url", "UserId", "SessionId", "Timestamp", "Duration", "Event", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
