# Deprecated v1 properties without conversion in v2
protocol=protocol
sslcerttype=sslcerttype
sslkeyalg=sslkeyalg
sslprotocol=sslprotocol
custom_socket_factory=custom_socket_factory
custom_socket_factory_options=custom_socket_factory_options
socket_ip_tos=socket_ip_tos
http_connection_provider=http_connection_provider
http_server_default_response=http_server_default_response
receive_query_progress=receive_query_progress
send_http_client_id=send_http_client_id
ahc_validate_after_inactivity=ahc_validate_after_inactivity
ahc_retry_on_failure=ahc_retry_on_failure
use_compilation=use_compilation
debug_measure_request_time=debug_measure_request_time
max_scheduler_threads=max_scheduler_threads
max_requests=max_requests
thread_keepalive_timeout=thread_keepalive_timeout
max_core_thread_ttl=max_core_thread_ttl
auto_discovery=auto_discovery
load_balancing_policy=load_balancing_policy
load_balancing_tags=load_balancing_tags
health_check_interval=health_check_interval
health_check_method=health_check_method
node_discovery_interval=node_discovery_interval
node_discovery_limit=node_discovery_limit
node_check_interval=node_check_interval
node_group_size=node_group_size
check_all_nodes=check_all_nodes
failover=failover
auto_session=auto_session
log_leading_comment=log_leading_comment
rename_response_column=rename_response_column
transaction_timeout=transaction_timeout
repeat_on_session_lock=repeat_on_session_lock
buffering=buffering
buffer_queue_variation=buffer_queue_variation
use_blocking_queue=use_blocking_queue
read_buffer_size=read_buffer_size
write_buffer_size=write_buffer_size
request_chunk_size=request_chunk_size
request_buffering=request_buffering
response_buffering=response_buffering
compress_algorithm=compress_algorithm
decompress_algorithm=decompress_algorithm
compress_level=compress_level
decompress_level=decompress_level
max_buffer_size=max_buffer_size
max_mapper_cache=max_mapper_cache
max_queued_buffers=max_queued_buffers
max_queued_requests=max_queued_requests
rounding_mode=rounding_mode
srv_resolve=srv_resolve
reuse_value_wrapper=reuse_value_wrapper
widen_unsigned_types=widen_unsigned_types
use_objects_in_arrays=use_objects_in_arrays
use_server_time_zone_for_dates=use_server_time_zone_for_dates
