# Known client and driver options in v1 (0.7.1)
async=async
auto_discovery=auto_discovery
custom_settings=custom_settings
custom_socket_factory=custom_socket_factory
custom_socket_factory_options=custom_socket_factory_options
load_balancing_policy=load_balancing_policy
load_balancing_tags=load_balancing_tags
health_check_interval=health_check_interval
health_check_method=health_check_method
node_discovery_interval=node_discovery_interval
node_discovery_limit=node_discovery_limit
node_check_interval=node_check_interval
node_group_size=node_group_size
check_all_nodes=check_all_nodes
buffer_size=buffer_size
buffer_queue_variation=buffer_queue_variation
read_buffer_size=read_buffer_size
write_buffer_size=write_buffer_size
request_chunk_size=request_chunk_size
request_buffering=request_buffering
response_buffering=response_buffering
client_name=client_name
compress=compress
decompress=decompress
compress_algorithm=compress_algorithm
decompress_algorithm=decompress_algorithm
compress_level=compress_level
decompress_level=decompress_level
connect_timeout=connect_timeout
database=database
failover=failover
format=format
log_leading_comment=log_leading_comment
max_buffer_size=max_buffer_size
max_mapper_cache=max_mapper_cache
max_execution_time=max_execution_time
max_queued_buffers=max_queued_buffers
max_queued_requests=max_queued_requests
max_result_rows=max_result_rows
result_overflow_mode=result_overflow_mode
max_threads_per_client=max_threads_per_client
max_core_thread_ttl=max_core_thread_ttl
product_name=product_name
rename_response_column=rename_response_column
retry=retry
repeat_on_session_lock=repeat_on_session_lock
reuse_value_wrapper=reuse_value_wrapper
server_revision=server_revision
server_time_zone=server_time_zone
server_version=server_version
session_id=session_id
session_check=session_check
session_timeout=session_timeout
socket_timeout=socket_timeout
socket_reuseaddr=socket_reuseaddr
socket_keepalive=socket_keepalive
socket_linger=socket_linger
socket_ip_tos=socket_ip_tos
socket_tcp_nodelay=socket_tcp_nodelay
socket_rcvbuf=socket_rcvbuf
socket_sndbuf=socket_sndbuf
ssl=ssl
sslmode=sslmode
sslrootcert=sslrootcert
sslcert=sslcert
sslkey=sslkey
key_store_type=key_store_type
trust_store=trust_store
key_store_password=key_store_password
transaction_timeout=transaction_timeout
widen_unsigned_types=widen_unsigned_types
use_binary_string=use_binary_string
use_blocking_queue=use_blocking_queue
use_compilation=use_compilation
use_objects_in_arrays=use_objects_in_arrays
proxy_type=proxy_type
proxy_host=proxy_host
proxy_port=proxy_port
proxy_username=proxy_username
proxy_password=proxy_password
use_server_time_zone=use_server_time_zone
use_server_time_zone_for_dates=use_server_time_zone_for_dates
use_time_zone=use_time_zone
query_id=query_id
connection_ttl=connection_ttl
debug_measure_request_time=debug_measure_request_time
ssl_socket_sni=ssl_socket_sni
http_connection_provider=http_connection_provider
custom_http_headers=custom_http_headers
custom_headers=custom_headers
custom_http_params=custom_http_params
custom_params=custom_params
http_server_default_response=http_server_default_response
http_keep_alive=http_keep_alive
max_open_connections=max_open_connections
receive_query_progress=receive_query_progress
send_http_client_id=send_http_client_id
wait_end_of_query=wait_end_of_query
remember_last_set_roles=remember_last_set_roles
ahc_validate_after_inactivity=ahc_validate_after_inactivity
ahc_retry_on_failure=ahc_retry_on_failure
connection_reuse_strategy=connection_reuse_strategy
alive_timeout=alive_timeout
http_use_basic_auth=http_use_basic_auth
autoCommit=autoCommit
createDatabaseIfNotExist=createDatabaseIfNotExist
continueBatchOnError=continueBatchOnError
databaseTerm=databaseTerm
dialect=dialect
externalDatabase=externalDatabase
fetchSize=fetchSize
localFile=localFile
jdbcCompliant=jdbcCompliant
namedParameter=namedParameter
nullAsDefault=nullAsDefault
transactionSupport=transactionSupport
typeMappings=typeMappings
wrapperObject=wrapperObject
user=user
password=password
protocol=protocol
sslcerttype=sslcerttype
sslkeyalg=sslkeyalg
sslprotocol=sslprotocol
max_scheduler_threads=max_scheduler_threads
max_requests=max_requests
thread_keepalive_timeout=thread_keepalive_timeout
buffering=buffering
time_zone=time_zone
version=version
