# Property mappings from v1 keys to v2 keys
connect_timeout=connection_timeout
buffer_size=client_network_buffer_size
sslmode=ssl_mode
sslkey=ssl_key
proxy_username=proxy_user
alive_timeout=http_keep_alive_timeout
http_keep_alive=http_keep_alive_timeout
version=server_version
server_revision=server_version
time_zone=server_time_zone
product_name=client_name
use_binary_string=binary_string_support
typeMappings=jdbc_type_mappings
databaseTerm=jdbc_schema_term
