# Property mappings from v1 keys to v2 keys
connect_timeout=connection_timeout
buffer_size=client_network_buffer_size
sslmode=ssl_mode
sslkey=ssl_key
proxy_username=proxy_user
alive_timeout=http_keep_alive_timeout
typeMappings=jdbc_type_mappings
databaseTerm=jdbc_schema_term
