# Known client and driver options in v2 (0.9.8)
session_db_roles=session_db_roles
http_use_basic_auth=http_use_basic_auth
user=user
password=password
max_open_connections=max_open_connections
http_keep_alive_timeout=http_keep_alive_timeout
use_server_time_zone=use_server_time_zone
use_time_zone=use_time_zone
server_version=server_version
server_time_zone=server_time_zone
async=async
connection_ttl=connection_ttl
connection_timeout=connection_timeout
connection_reuse_strategy=connection_reuse_strategy
socket_timeout=socket_timeout
socket_rcvbuf=socket_rcvbuf
socket_sndbuf=socket_sndbuf
socket_reuseaddr=socket_reuseaddr
socket_keepalive=socket_keepalive
socket_tcp_nodelay=socket_tcp_nodelay
socket_linger=socket_linger
database=database
compress=compress
decompress=decompress
client.use_http_compression=client.use_http_compression
compression.lz4.uncompressed_buffer_size=compression.lz4.uncompressed_buffer_size
disable_native_compression=disable_native_compression
proxy_type=proxy_type
proxy_host=proxy_host
proxy_port=proxy_port
proxy_user=proxy_user
proxy_password=proxy_password
max_execution_time=max_execution_time
trust_store=trust_store
key_store_type=key_store_type
ssl_key_store=ssl_key_store
key_store_password=key_store_password
ssl_key=ssl_key
sslrootcert=sslrootcert
sslcert=sslcert
ssl_mode=ssl_mode
ssl_context=ssl_context
retry=retry
format=format
max_threads_per_client=max_threads_per_client
query_id=query_id
client_network_buffer_size=client_network_buffer_size
access_token=access_token
ssl_authentication=ssl_authentication
connection_pool_enabled=connection_pool_enabled
connection_request_timeout=connection_request_timeout
client_retry_on_failures=client_retry_on_failures
client_name=client_name
product_name=product_name
bearer_token=bearer_token
app_compressed_data=app_compressed_data
metrics_name=metrics_name
client.http.cookies_enabled=client.http.cookies_enabled
client_allow_binary_reader_to_reuse_buffers=client_allow_binary_reader_to_reuse_buffers
type_hint_mapping=type_hint_mapping
binary_string_support=binary_string_support
ssl_socket_sni=ssl_socket_sni
client.http.use_form_request_for_query=client.http.use_form_request_for_query
json_disable_number_quoting=json_disable_number_quoting
custom_settings_prefix=custom_settings_prefix
ssl_cipher_suites=ssl_cipher_suites

# JDBC Driver V2 specific properties
jdbc_ignore_unsupported_values=jdbc_ignore_unsupported_values
jdbc_schema_term=jdbc_schema_term
ssl=ssl
default_query_settings=default_query_settings
beta.row_binary_for_simple_insert=beta.row_binary_for_simple_insert
jdbc_resultset_auto_close=jdbc_resultset_auto_close
jdbc_use_max_result_rows=jdbc_use_max_result_rows
jdbc_sql_parser=jdbc_sql_parser
jdbc_query_id_generator=jdbc_query_id_generator
remember_last_set_roles=remember_last_set_roles
custom_http_params=custom_http_params
custom_settings=custom_settings
use_server_time_zone_for_dates=use_server_time_zone_for_dates
http_connection_provider=http_connection_provider
jdbc_cluster_name=jdbc_cluster_name
jdbc_type_mappings=jdbc_type_mappings
typeMappings=typeMappings
jdbc_json_parser_factory=jdbc_json_parser_factory
