/*
 * This source file was generated by the Gradle 'init' task
 */
package com.clickhouse.examples.arrow_server;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppArrowServerTest {
    @Test public void appHasAGreeting() {
        AppArrowServer classUnderTest = new AppArrowServer();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
